### ISSUE TITLE
Source for dwm missing

### ISSUE THREAD

**Issue by Mihaylov93** [clockworkpi/launcher#307]
There is a binary in the launcher to which we dont have the source.
https://github.com/clockworkpi/launcher/blob/master/dwm-mod

**Comment by Godzil** [comment]
It's sad, but even if I think they just forgot about it, DWM is under a [MIT license](https://git.suckless.org/dwm/file/LICENSE.html), they are not forced to release their changes.

And to be honest, as DMW is "[configured at compilation](https://git.suckless.org/dwm/file/README.html#l45)" I'm pretty sure the only changes are the configuration.

**Comment by cuu** [comment]
actually , this is awkward, I lost the source of this dwm ,too
back at that time I was doing a little mods in dwm to get it working because it is the only WM can work under the lima, but now, the new lima can work with any WM ,so this is not a problem 
in the next os image we will remove the dwm 
thanks

**Comment by Mihaylov93** [comment]
> the new lima can work with any WM ,so this is not a problem anymore
> in the next os image we will remove the dwm

The new OS is out and dmw binary is still there, and used.
